# Generated by Django 6.1 on 2026-08-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
